# Generated by Django 4.2.6 on 2023-11-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('piggyBankApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piggybank',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
    ]
